// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package templates

import (
	"embed"
	"os"
	"strconv"
	"strings"
	"sync"
	"text/template"
)

// CLITemplatesFS contains all CLI usage templates.
//
//go:embed *.txt
var CLITemplatesFS embed.FS

var (
	compiledTemplates *template.Template
	templatesOnce     sync.Once
)

func getTerminalWidth() int {
	if w, err := strconv.Atoi(os.Getenv("COLUMNS")); err == nil && w > 0 {
		return w
	}
	return 80 // fallback
}

func wrapText(text string, indent int, width int) string {
	if width <= indent {
		width = indent + 10 // minimum sensible width
	}
	avail := width - indent
	indentStr := "\n" + strings.Repeat(" ", indent)

	var out strings.Builder
	lines := strings.Split(text, "\n")

	for i, line := range lines {
		if i > 0 {
			out.WriteString(indentStr)
		}

		words := strings.Fields(line)
		if len(words) == 0 {
			continue
		}

		currentLen := 0
		for j, word := range words {
			if j > 0 && currentLen+1+len(word) > avail {
				out.WriteString(indentStr)
				currentLen = 0
			} else if j > 0 {
				out.WriteString(" ")
				currentLen++
			}
			out.WriteString(word)
			currentLen += len(word)
		}
	}
	return out.String()
}

func wrapFlag(maxFlag, maxDef, width int, flagStr, defStr, descStr string) string {
	indent := 4 + maxFlag + 1 + maxDef + 1 // 4 spaces for initial indent + columns + spacing
	wrappedDesc := wrapText(descStr, indent, width)
	return wrappedDesc
}

func GetTemplates() *template.Template {
	templatesOnce.Do(func() {
		width := getTerminalWidth()

		funcs := template.FuncMap{
			"wrapFlag": func(maxFlag, maxDef int, flagStr, defStr, descStr string) string {
				indent := 4 + maxFlag + 1
				if maxDef > 0 {
					indent += maxDef + 1
				}
				if descStr == "" {
					return ""
				}
				return wrapText(descStr, indent, width)
			},
		}

		compiledTemplates = template.Must(template.New("").Funcs(funcs).ParseFS(CLITemplatesFS, "*.txt"))
	})
	return compiledTemplates
}
