// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"txtar/cli"
)

var _ Cmd = (*Add)(nil)

type Add struct {
	*RootCmd
	Flags         *flag.FlagSet
	recursive     bool
	follow        bool
	archive       string
	files         []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Add) error
}

type UsageDataAdd struct {
	*Add
	Recursive bool
}

func (c *Add) Usage() {
	err := executeUsage(os.Stderr, "add_usage.txt", UsageDataAdd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Add) UsageRecursive() {
	err := executeUsage(os.Stderr, "add_usage.txt", UsageDataAdd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Add) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "recursive":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.recursive = b
				} else {
					c.recursive = true
				}

			case "follow":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.follow = b
				} else {
					c.follow = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "r" {
					found = true
					c.recursive = true
				}

				if char == "f" {
					found = true
					c.follow = true
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument archive
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.archive = argVal
		} else {
		}
	}
	// Handle vararg files
	{
		varArgStart := 1
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.files = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("add failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewAdd() *Add {
	set := flag.NewFlagSet("add", flag.ContinueOnError)
	v := &Add{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.recursive, "recursive", false, "Recursive")
	set.BoolVar(&v.recursive, "r", false, "Recursive")

	set.BoolVar(&v.follow, "follow", false, "Follow symlinks")
	set.BoolVar(&v.follow, "f", false, "Follow symlinks")
	set.Usage = v.Usage

	v.CommandAction = func(c *Add) error {

		cli.Add(c.recursive, c.follow, c.archive, c.files...)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
