// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestAdd_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewAdd()

	called := false
	cmd.CommandAction = func(c *Add) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--recursive")
	args = append(args, "--follow")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.recursive != true {
		t.Errorf("Expected recursive to be true, got '%v'", cmd.recursive)
	}
	if cmd.follow != true {
		t.Errorf("Expected follow to be true, got '%v'", cmd.follow)
	}
	if cmd.archive != "test" {
		t.Errorf("Expected archive to be 'test', got '%v'", cmd.archive)
	}
}
