// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestCat_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewCat()

	called := false
	cmd.CommandAction = func(c *Cat) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "test")
	args = append(args, "--txt")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.archive != "test" {
		t.Errorf("Expected archive to be 'test', got '%v'", cmd.archive)
	}
	if cmd.txt != true {
		t.Errorf("Expected txt to be true, got '%v'", cmd.txt)
	}
}
