// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"txtar/cli"
)

var _ Cmd = (*Create)(nil)

type Create struct {
	*RootCmd
	Flags         *flag.FlagSet
	recursive     bool
	trim          bool
	follow        bool
	name          string
	depth         int
	files         []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Create) error
}

type UsageDataCreate struct {
	*Create
	Recursive bool
}

func (c *Create) Usage() {
	err := executeUsage(os.Stderr, "create_usage.txt", UsageDataCreate{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Create) UsageRecursive() {
	err := executeUsage(os.Stderr, "create_usage.txt", UsageDataCreate{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Create) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "recursive":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.recursive = b
				} else {
					c.recursive = true
				}

			case "trim":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.trim = b
				} else {
					c.trim = true
				}

			case "follow":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.follow = b
				} else {
					c.follow = true
				}

			case "name":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.name = value

			case "depth":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.depth = v
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "r" {
					found = true
					c.recursive = true
				}

				if char == "t" {
					found = true
					c.trim = true
				}

				if char == "f" {
					found = true
					c.follow = true
				}

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	// Handle vararg files
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.files = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("create failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewCreate() *Create {
	set := flag.NewFlagSet("create", flag.ContinueOnError)
	v := &Create{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.recursive, "recursive", false, "Recursive")
	set.BoolVar(&v.recursive, "r", false, "Recursive")

	set.BoolVar(&v.trim, "trim", false, "Trim directory prefix")
	set.BoolVar(&v.trim, "t", false, "Trim directory prefix")

	set.BoolVar(&v.follow, "follow", false, "Follow symlinks")
	set.BoolVar(&v.follow, "f", false, "Follow symlinks")

	set.StringVar(&v.name, "name", "", "Name filter (glob pattern)")

	set.IntVar(&v.depth, "depth", -1, "Max depth")
	set.Usage = v.Usage

	v.CommandAction = func(c *Create) error {

		cli.Create(c.recursive, c.trim, c.follow, c.name, c.depth, c.files...)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
