// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestCreate_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewCreate()

	called := false
	cmd.CommandAction = func(c *Create) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--recursive")
	args = append(args, "--trim")
	args = append(args, "--follow")
	args = append(args, "--name")
	args = append(args, "test")
	args = append(args, "--depth")
	args = append(args, "1")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.recursive != true {
		t.Errorf("Expected recursive to be true, got '%v'", cmd.recursive)
	}
	if cmd.trim != true {
		t.Errorf("Expected trim to be true, got '%v'", cmd.trim)
	}
	if cmd.follow != true {
		t.Errorf("Expected follow to be true, got '%v'", cmd.follow)
	}
	if cmd.name != "test" {
		t.Errorf("Expected name to be 'test', got '%v'", cmd.name)
	}
	if cmd.depth != 1 {
		t.Errorf("Expected depth to be 1, got '%v'", cmd.depth)
	}
}

func TestCreate_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewCreate()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
