// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestDescription_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewDescription()

	called := false
	cmd.CommandAction = func(c *Description) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--replace")
	args = append(args, "--append")
	args = append(args, "--edit")
	args = append(args, "test")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.replace != true {
		t.Errorf("Expected replace to be true, got '%v'", cmd.replace)
	}
	if cmd.appendDesc != true {
		t.Errorf("Expected appendDesc to be true, got '%v'", cmd.appendDesc)
	}
	if cmd.edit != "test" {
		t.Errorf("Expected edit to be 'test', got '%v'", cmd.edit)
	}
	if cmd.archive != "test" {
		t.Errorf("Expected archive to be 'test', got '%v'", cmd.archive)
	}
}

func TestDescription_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewDescription()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
