// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"txtar/cli"
)

var _ Cmd = (*Description)(nil)

type Description struct {
	*RootCmd
	Flags         *flag.FlagSet
	replace       bool
	appendDesc    bool
	edit          string
	archive       string
	text          []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Description) error
}

type UsageDataDescription struct {
	*Description
	Recursive bool
}

func (c *Description) Usage() {
	err := executeUsage(os.Stderr, "description_usage.txt", UsageDataDescription{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Description) UsageRecursive() {
	err := executeUsage(os.Stderr, "description_usage.txt", UsageDataDescription{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Description) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "replace":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.replace = b
				} else {
					c.replace = true
				}

			case "appendDesc", "append":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.appendDesc = b
				} else {
					c.appendDesc = true
				}

			case "edit":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.edit = value
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "r" {
					found = true
					c.replace = true
				}

				if char == "a" {
					found = true
					c.appendDesc = true
				}

				if char == "e" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.edit = value
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument archive
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.archive = argVal
		} else {
		}
	}
	// Handle vararg text
	{
		varArgStart := 1
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.text = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("description failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewDescription() *Description {
	set := flag.NewFlagSet("description", flag.ContinueOnError)
	v := &Description{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.replace, "replace", false, "Replace description")
	set.BoolVar(&v.replace, "r", false, "Replace description")

	set.BoolVar(&v.appendDesc, "append", false, "Append to description")
	set.BoolVar(&v.appendDesc, "a", false, "Append to description")

	set.StringVar(&v.edit, "edit", "", "Edit specific lines (format: <start>-<end>)")
	set.StringVar(&v.edit, "e", "", "Edit specific lines (format: <start>-<end>)")
	set.Usage = v.Usage

	v.CommandAction = func(c *Description) error {

		cli.Description(c.replace, c.appendDesc, c.edit, c.archive, c.text...)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
