// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestExtract_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewExtract()

	called := false
	cmd.CommandAction = func(c *Extract) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--verbose")
	args = append(args, "--dir")
	args = append(args, "test")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.verbose != true {
		t.Errorf("Expected verbose to be true, got '%v'", cmd.verbose)
	}
	if cmd.dir != "test" {
		t.Errorf("Expected dir to be 'test', got '%v'", cmd.dir)
	}
	if cmd.archive != "test" {
		t.Errorf("Expected archive to be 'test', got '%v'", cmd.archive)
	}
}

func TestExtract_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewExtract()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
