// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"
	"txtar/cli"
)

var _ Cmd = (*List)(nil)

type List struct {
	*RootCmd
	Flags         *flag.FlagSet
	archive       string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *List) error
}

type UsageDataList struct {
	*List
	Recursive bool
}

func (c *List) Usage() {
	err := executeUsage(os.Stderr, "list_usage.txt", UsageDataList{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *List) UsageRecursive() {
	err := executeUsage(os.Stderr, "list_usage.txt", UsageDataList{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *List) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument archive
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.archive = argVal
		} else {
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("list failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewList() *List {
	set := flag.NewFlagSet("list", flag.ContinueOnError)
	v := &List{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}
	set.Usage = v.Usage

	v.CommandAction = func(c *List) error {

		cli.List(c.archive)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
