// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSkillList_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewSkillList()

	called := false
	cmd.CommandAction = func(c *SkillList) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--format")
	args = append(args, "test")
	args = append(args, "--scope")
	args = append(args, "test")
	args = append(args, "--agent")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.format != "test" {
		t.Errorf("Expected format to be 'test', got '%v'", cmd.format)
	}
	if cmd.scope != "test" {
		t.Errorf("Expected scope to be 'test', got '%v'", cmd.scope)
	}
	if cmd.agent != "test" {
		t.Errorf("Expected agent to be 'test', got '%v'", cmd.agent)
	}
}
