// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSkillUpdate_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewSkillUpdate()

	called := false
	cmd.CommandAction = func(c *SkillUpdate) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--all")
	args = append(args, "--force")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.all != true {
		t.Errorf("Expected all to be true, got '%v'", cmd.all)
	}
	if cmd.force != true {
		t.Errorf("Expected force to be true, got '%v'", cmd.force)
	}
}
