// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"errors"
	"txtar/cli"
	"txtar/cmd"
)

var _ Cmd = (*SkillInstall)(nil)

type SkillInstall struct {
	*RootCmd
	Flags         *flag.FlagSet
	scope         string
	agent         string
	source        string
	nameOrPath    []string
	SubCommands   map[string]Cmd
	CommandAction func(c *SkillInstall) error
}

type UsageDataSkillInstall struct {
	*SkillInstall
	Recursive bool
}

func (c *SkillInstall) Usage() {
	err := executeUsage(os.Stderr, "skill-install_usage.txt", UsageDataSkillInstall{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SkillInstall) UsageRecursive() {
	err := executeUsage(os.Stderr, "skill-install_usage.txt", UsageDataSkillInstall{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SkillInstall) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "scope":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.scope = value

			case "agent":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.agent = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	if len(remainingArgs) < 1 {
		return fmt.Errorf("expected at least 1 positional arguments, got %d", len(remainingArgs))
	}
	// Handle positional argument source
	{
		argIndex := 0
		if argIndex >= 0 && argIndex < len(remainingArgs) {
			argVal := remainingArgs[argIndex]
			c.source = argVal
		}
	}
	// Handle vararg nameOrPath
	{
		varArgStart := 1
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.nameOrPath = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("skill-install failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewSkillInstall() *SkillInstall {
	set := flag.NewFlagSet("skill-install", flag.ContinueOnError)
	v := &SkillInstall{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.scope, "scope", "user", "Installation scope user or project")

	set.StringVar(&v.agent, "agent", "", "Target agent e.g. codex claude copilot cursor")
	set.Usage = v.Usage

	v.CommandAction = func(c *SkillInstall) error {

		err := cli.SkillInstall(c.scope, c.agent, c.source, c.nameOrPath...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("skill-install failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
